-- Predetermined system-wide indicators with calculation weights.
-- Hundreds of granular physical, hormonal, lifestyle, aesthetic, and behavioral signals.
-- High weight (>= 7.0) = strong explicit signal (immediate shift).
-- Low weight (< 7.0) = subtle secondary signal (accumulates toward shift).

INSERT INTO indicators_master (metric_name, phase_association, mathematical_weight) VALUES
    ('Overcoat', 'period', 9.0),
    ('Heating Pad Use', 'period', 8.0),
    ('Chocolate Craving', 'period', 5.0),
    ('Irritability', 'period', 4.0),
    ('Bloating', 'period', 6.0),
    ('Comfort Food Order', 'period', 3.0),
    ('Sweatpants', 'period', 5.0),
    ('Acne Flare-Up', 'period', 3.5),
    ('Mini Skirt', 'ovulation', 9.0),
    ('Increased Flirtatiousness', 'ovulation', 7.5),
    ('Heightened Libido', 'ovulation', 8.5),
    ('Extra Makeup Effort', 'ovulation', 5.0),
    ('New Outfit Purchase', 'ovulation', 4.5),
    ('Increased Sociability', 'ovulation', 4.0),
    ('Perfume Use', 'ovulation', 3.0),
    ('High Energy Level', 'ovulation', 3.5),
    ('Menstrual Flow (Active Bleeding)', 'period', 9.5),
    ('Tampon / Pad Usage', 'period', 9.5),
    ('Menstrual Cup Insertion', 'period', 9.5),
    ('Period Underwear Worn', 'period', 9.0),
    ('Pelvic Uterine Cramping', 'period', 8.5),
    ('Lower Back Ache (Dull / Radiating)', 'period', 7.5),
    ('Inner Thigh Aching / Heaviness', 'period', 6.5),
    ('Basal Body Temperature Drop', 'period', 7.0),
    ('Breast Soreness & Tenderness', 'period', 7.0),
    ('Breast Swelling / Heaviness', 'period', 6.5),
    ('Fluid Retention & Swollen Fingers', 'period', 6.0),
    ('Water Weight Gain (1-3 lbs)', 'period', 5.5),
    ('Puffy Eyelids / Facial Water Retention', 'period', 5.0),
    ('Abdominal Distension / Bloat', 'period', 6.5),
    ('Gastrointestinal Sluggishness / Constipation', 'period', 5.5),
    ('Pre-flow Loose Stools / Diarrhea', 'period', 7.0),
    ('Frequent Urination (Prostaglandin Effect)', 'period', 5.5),
    ('Deep Pelvic Fullness / Pressure', 'period', 6.5),
    ('Restless Legs Syndrome Flare', 'period', 5.0),
    ('Muscle Stiffness & Sore Joints', 'period', 5.5),
    ('Migraine (Catamenial / Hormonal)', 'period', 7.5),
    ('Tension Headache (Forehead/Neck)', 'period', 6.0),
    ('Extreme Physical Lethargy', 'period', 6.5),
    ('Cold Intolerance / Chills', 'period', 6.0),
    ('Night Sweats / Hot Flashes (Luteal)', 'period', 6.0),
    ('Skin Greasiness / Sebum Spike', 'period', 5.5),
    ('Chin & Jawline Cystic Breakouts', 'period', 6.5),
    ('Greasy Hair / Rapid Scalp Oiliness', 'period', 5.0),
    ('Increased Hair Shedding', 'period', 4.5),
    ('Lower Physical Stamina', 'period', 5.5),
    ('Elevated Resting Heart Rate (Late Luteal)', 'period', 5.0),
    ('Dizziness / Orthostatic Lightheadedness', 'period', 5.5),
    ('Vaginal Dryness / Low Discharge', 'period', 6.0),
    ('Dark Brown Spotting (Pre/Post Menses)', 'period', 8.5),
    ('Sensitivity to Pain / Lower Pain Threshold', 'period', 5.5),
    ('Sinus Congestion (Hormonal Rhinitis)', 'period', 4.0),
    ('Nausea / Queasy Stomach (Prostaglandin)', 'period', 6.0),
    ('Egg White Cervical Mucus (EWCM)', 'ovulation', 9.5),
    ('Positive LH Ovulation Surge Test', 'ovulation', 9.5),
    ('Mittelschmerz (One-sided Ovary Twinge)', 'ovulation', 8.5),
    ('High, Soft, Open Cervix (SHOW Sign)', 'ovulation', 8.5),
    ('Basal Body Temperature Nadir (Pre-ovulation Dip)', 'ovulation', 8.0),
    ('Ovulation Spotting (Pink/Light Brown)', 'ovulation', 8.0),
    ('Heightened Olfactory Sensitivity', 'ovulation', 5.5),
    ('Enhanced Skin Glow / Luminosity', 'ovulation', 6.0),
    ('Clear Blemish-Free Complexion', 'ovulation', 5.5),
    ('Slightly Rosier Facial Flush', 'ovulation', 5.0),
    ('Symmetrical Facial Attractiveness Peak', 'ovulation', 5.5),
    ('Plumper Lip Appearance', 'ovulation', 4.5),
    ('Higher-Pitched Vocal Tone', 'ovulation', 5.5),
    ('Peak Physical Strength / PR Lift in Gym', 'ovulation', 6.5),
    ('Higher Cardiovascular Endurance', 'ovulation', 6.0),
    ('Lower Resting Heart Rate (Follicular)', 'ovulation', 5.0),
    ('Decreased Appetite / Natural Fasting Ease', 'ovulation', 5.5),
    ('Quick Muscle Recovery', 'ovulation', 5.0),
    ('Naturally Moist & Lubricated Vagina', 'ovulation', 7.5),
    ('Heightened Tactile Sensitivity', 'ovulation', 6.0),
    ('Reduced Sensitivity to Cold', 'ovulation', 5.0),
    ('Leaner Waist Definition', 'ovulation', 5.0),
    ('Faster Reflexes & Coordination', 'ovulation', 5.0),
    ('Social Withdrawal / Canceling Plans', 'period', 7.0),
    ('Staying In Bed / Duvet Day', 'period', 7.5),
    ('Binge-Watching Comfort TV Series', 'period', 5.5),
    ('Irritability with Partner / Loved Ones', 'period', 6.0),
    ('Low Patience / Short Fuse', 'period', 5.5),
    ('Overthinking Past Regrets / Rumination', 'period', 5.0),
    ('Crying Over Trivial / Emotional Triggers', 'period', 6.5),
    ('Heightened Anxiety / Impending Dread', 'period', 6.0),
    ('Rejection Sensitive Dysphoria Flare', 'period', 5.5),
    ('Brain Fog / Forgetfulness', 'period', 5.5),
    ('Difficulty Concentrating on Work', 'period', 5.5),
    ('Imposter Syndrome Spike', 'period', 4.5),
    ('Zero Sexual Desire / Aversion to Touch', 'period', 7.5),
    ('Need for Solitude & Quiet Environments', 'period', 6.0),
    ('Overwhelmed by Noise & Bright Lights', 'period', 5.0),
    ('Nesting & Reorganizing Drawers/Closets', 'period', 4.5),
    ('Excessive Online Shopping for Cozy Items', 'period', 4.0),
    ('Postponing Tough Conversations', 'period', 5.0),
    ('Self-Critical Mirror Viewing', 'period', 5.0),
    ('Emotional Vulnerability / Seeking Reassurance', 'period', 5.5),
    ('Spontaneous Social Organizing / Group Host', 'ovulation', 6.5),
    ('Initiating Flirty Text Conversations', 'ovulation', 7.5),
    ('High Confidence in Professional Meetings', 'ovulation', 6.0),
    ('Feeling Unapologetically Attractive', 'ovulation', 7.0),
    ('High Risk Tolerance & Adventurous Spirit', 'ovulation', 5.5),
    ('Desire to Go Dancing / Nightclubs / Bars', 'ovulation', 7.0),
    ('Intense Daydreaming About Romance / Intimacy', 'ovulation', 7.5),
    ('Initiating Sex with Partner', 'ovulation', 8.5),
    ('Seeking Novel Experiences / Spontaneous Outings', 'ovulation', 6.0),
    ('Talkative / Fast Speech Flow & Eloquence', 'ovulation', 5.5),
    ('High Empathy & Easy Bonding with Strangers', 'ovulation', 5.0),
    ('Optimistic Future-Oriented Mindset', 'ovulation', 5.5),
    ('Creative Work Breakthroughs / Ideas Boom', 'ovulation', 5.5),
    ('Willingness to Try Risky Fashion Choices', 'ovulation', 6.5),
    ('Strong Assertiveness & Direct Communication', 'ovulation', 5.5),
    ('Desire for Physical Closeness & Hugs', 'ovulation', 6.0),
    ('Posting Active Photos / Selfies Online', 'ovulation', 6.5),
    ('Browsing Dating Apps / Swiping Actively', 'ovulation', 7.0),
    ('Wearing Baggy Oversized Hoodie', 'period', 6.5),
    ('Elastic Waistband Pants Only', 'period', 7.0),
    ('Thick Woolen Socks / Slippers All Day', 'period', 6.0),
    ('Wearing Dark Bottoms (Black / Navy Pants)', 'period', 7.0),
    ('Boyfriend Cut / Loose Jeans', 'period', 6.0),
    ('No-Wire Bralette / Going Braless', 'period', 6.5),
    ('Hair Thrown Into Messy Bun', 'period', 5.5),
    ('Zero Makeup / Bare Face Routine', 'period', 6.0),
    ('Layered Knits & Cardigans', 'period', 5.5),
    ('Comfortable Flats or Slip-On UGGs', 'period', 6.0),
    ('Avoiding Form-Fitting Dresses', 'period', 6.5),
    ('Wearing Old High-Waist Cotton Briefs', 'period', 7.5),
    ('Carrying Extra Heavy-Duty Handbag (Supplies)', 'period', 5.0),
    ('Choosing Subdued / Neutral / Black Colors', 'period', 5.0),
    ('Refusing Stiff Denim or Belts', 'period', 6.5),
    ('Form-Fitting Bodycon Dress', 'ovulation', 8.5),
    ('Plunging Neckline / Backless Top', 'ovulation', 8.0),
    ('Lace or Satin Lingerie Selection', 'ovulation', 8.5),
    ('Push-Up / Underwire Balconette Bra', 'ovulation', 7.0),
    ('High Heels / Strappy Stilettos', 'ovulation', 7.5),
    ('Vibrant Red / Pink / Bright Colors', 'ovulation', 6.5),
    ('Fresh Blowout / Styled Hair', 'ovulation', 6.0),
    ('Full Glam Makeup & Bold Lip Color', 'ovulation', 6.5),
    ('Prominent Jewelry / Gold Hoops / Bangles', 'ovulation', 5.5),
    ('Shaved Legs & Fresh Body Exfoliation', 'ovulation', 6.5),
    ('Floral / Musky Seductive Fragrance', 'ovulation', 6.5),
    ('Fitted Crop Top & High-Rise Slacks', 'ovulation', 7.0),
    ('Open-Front Sheer Blouse', 'ovulation', 7.5),
    ('Showing Midriff / Shoulder Exposure', 'ovulation', 7.0),
    ('Designer Bag Out for Evening', 'ovulation', 5.5),
    ('Craving Salty Chips / Crisps', 'period', 6.0),
    ('Carbohydrate Binge (Pasta / Pizza / Bread)', 'period', 6.5),
    ('Craving Red Meat / Burger / Steak (Iron Need)', 'period', 6.5),
    ('Late Night Sweet Tooth / Ice Cream', 'period', 6.0),
    ('Hot Herbal Tea (Chamomile / Peppermint / Ginger)', 'period', 5.5),
    ('Large Hot Broth / Ramen / Stew', 'period', 5.5),
    ('Sipping Warm Water / Hot Lemon Water', 'period', 5.0),
    ('Intense Sugar Craving Mid-Afternoon', 'period', 5.5),
    ('Extra Shot of Espresso (Fighting Fatigue)', 'period', 5.5),
    ('Mindless Grazing Every 2 Hours', 'period', 6.0),
    ('Bloat Discomfort After Normal Meal', 'period', 6.0),
    ('Craving Cheese / Dairy Comfort Foods', 'period', 5.5),
    ('Alcohol Intolerance / Instant Hangover', 'period', 5.5),
    ('Skipping Cold Salads / Aversion to Raw Food', 'period', 5.0),
    ('Electrolyte Drink / Coconut Water Restock', 'period', 5.0),
    ('Light Fresh Salad Craving', 'ovulation', 5.5),
    ('Cold Pressed Green Juice / Smoothie', 'ovulation', 5.5),
    ('Naturally Modest Portion Sizes (Full Quickly)', 'ovulation', 6.0),
    ('Zero Interest in Heavy Carbs', 'ovulation', 5.0),
    ('Craving Seafood / Sushi / Raw Oysters', 'ovulation', 5.5),
    ('Enjoying Cocktails / Wine in Social Setting', 'ovulation', 6.0),
    ('High Alcohol Tolerance', 'ovulation', 5.5),
    ('High Hydration Drive (Drinking Lots of Cold Water)', 'ovulation', 5.0),
    ('Intermittent Fasting Completed Effortlessly', 'ovulation', 6.0),
    ('Craving Citrus / Crisp Apples / Berries', 'ovulation', 4.5),
    ('Spicy Food Appetite (Jalapenos / Wasabi)', 'ovulation', 5.0),
    ('Mindful Clean Eating Preference', 'ovulation', 5.0),
    ('10+ Hours Sleep & Still Exhausted', 'period', 7.0),
    ('Afternoon Power Nap Requirement (1-2 hr)', 'period', 6.5),
    ('Tossing & Turning in Bed / Luteal Insomnia', 'period', 6.0),
    ('Vivid Anxious Dreams / Nightmares', 'period', 5.5),
    ('Waking Up Heavy-Limbed / Sore', 'period', 6.0),
    ('Difficulty Getting Out of Bed in Morning', 'period', 6.5),
    ('Yawning Repeatedly Mid-Morning', 'period', 5.0),
    ('Snoozing Alarm 3+ Times', 'period', 5.5),
    ('Early Evening Bedtime (Before 9 PM)', 'period', 6.5),
    ('Restless Fragmented Sleep Quality', 'period', 6.0),
    ('Waking Early (6 AM) Feeling Fully Refreshed', 'ovulation', 6.5),
    ('Surplus Energy on 6 Hours Sleep', 'ovulation', 6.0),
    ('No Midday Slump or Crash', 'ovulation', 5.5),
    ('Late Night Socializing Without Fatigue', 'ovulation', 6.5),
    ('Morning Workout Completed with Enthusiasm', 'ovulation', 6.5),
    ('Restful Deep Stage Sleep', 'ovulation', 5.5),
    ('Fast Falling Asleep (<10 Minutes)', 'ovulation', 5.0),
    ('Zero Daytime Napping Desired', 'ovulation', 5.0),
    ('Bouncing Out of Bed with Alarm', 'ovulation', 5.5),
    ('Hot Epsom Salt Bath with Candles', 'period', 7.0),
    ('Postponing Gym / Exercise Class', 'period', 6.5),
    ('Gentle Restorative Yin Yoga Only', 'period', 6.0),
    ('Curling Up with a Book on Sofa', 'period', 5.5),
    ('Putting Phone on Do Not Disturb', 'period', 6.0),
    ('Ordering Delivery to Avoid Leaving House', 'period', 6.0),
    ('Using Acupressure Mat for Pain Relief', 'period', 6.0),
    ('Applying Magnesium Oil to Calves & Belly', 'period', 5.5),
    ('Wearing Loose Cotton Robe for Hours', 'period', 5.5),
    ('Turning Down Dinner Party Invitations', 'period', 6.5),
    ('Deep Organizing Old Photos / Sentimental Items', 'period', 4.5),
    ('Writing in Journal About Frustrations', 'period', 5.0),
    ('Lighting Heavy Scented Comfort Candles', 'period', 4.5),
    ('Drinking Hot Raspberry Leaf Tea', 'period', 6.0),
    ('Booking a Deep Tissue / Remedial Massage', 'period', 5.5),
    ('Using TENS Unit for Cramp Relief', 'period', 8.0),
    ('HIIT / Heavy Weight Training Session', 'ovulation', 6.5),
    ('Booking Waxing / Hair Removal Appointment', 'ovulation', 7.5),
    ('Booking Hair Stylist Salon Appointment', 'ovulation', 6.5),
    ('Purchasing New Lingerie / Underwear Set', 'ovulation', 8.0),
    ('Shopping for High-End Cosmetics / Lip Gloss', 'ovulation', 6.0),
    ('Attending Live Music Concert / Festival', 'ovulation', 6.5),
    ('Hosting Dinner Party or Drinks Event', 'ovulation', 6.5),
    ('Accepting Last-Minute Weekend Trip / Getaway', 'ovulation', 6.5),
    ('Taking Extra Selfies & Updating Dating Bio', 'ovulation', 7.5),
    ('Flirting with Barista / Bartender / Stranger', 'ovulation', 7.5),
    ('Prolonged Eye Contact with Attractive People', 'ovulation', 7.0),
    ('Booking Spa / Facial Treatment', 'ovulation', 5.5),
    ('Dancing Seductively in Living Room / Mirror', 'ovulation', 7.0),
    ('Pitching Bold Idea at Work Presentation', 'ovulation', 6.0),
    ('Trying a New Daring Workout / Pole / Dance Class', 'ovulation', 6.5),
    ('Spritzing Fragrance on Pulse Points Multiple Times', 'ovulation', 6.0),
    ('Spasmodic Cramps in Lower Abdomen', 'period', 7.5),
    ('Dull Constant Ache in Lower Abdomen', 'period', 6.5),
    ('Radiating Tension in Lower Abdomen', 'period', 6.0),
    ('Spasmodic Cramps in Sacrum', 'period', 7.5),
    ('Dull Constant Ache in Sacrum', 'period', 6.5),
    ('Radiating Tension in Sacrum', 'period', 6.0),
    ('Spasmodic Cramps in Inner Thighs', 'period', 7.5),
    ('Dull Constant Ache in Inner Thighs', 'period', 6.5),
    ('Radiating Tension in Inner Thighs', 'period', 6.0),
    ('Spasmodic Cramps in Hip Joints', 'period', 7.5),
    ('Dull Constant Ache in Hip Joints', 'period', 6.5),
    ('Radiating Tension in Hip Joints', 'period', 6.0),
    ('Spasmodic Cramps in Groin', 'period', 7.5),
    ('Dull Constant Ache in Groin', 'period', 6.5),
    ('Radiating Tension in Groin', 'period', 6.0),
    ('Sharp Transient Pain in Right Ovary Area (Ovulatory Twinge)', 'ovulation', 8.0),
    ('Ache & Throbbing in Right Ovary Area (Follicle Growth)', 'ovulation', 7.5),
    ('Sharp Transient Pain in Left Ovary Area (Ovulatory Twinge)', 'ovulation', 8.0),
    ('Ache & Throbbing in Left Ovary Area (Follicle Growth)', 'ovulation', 7.5),
    ('Intense Craving: Dark Chocolate (70%+)', 'period', 5.5),
    ('Intense Craving: Milk Chocolate Bar', 'period', 5.5),
    ('Intense Craving: Chocolate Chip Cookies', 'period', 5.5),
    ('Intense Craving: Brownies', 'period', 5.5),
    ('Intense Craving: Hot Cocoa with Marshmallows', 'period', 5.5),
    ('Intense Craving: Sea Salt Potato Chips', 'period', 5.5),
    ('Intense Craving: French Fries with Extra Salt', 'period', 5.5),
    ('Intense Craving: Cheesy Pizza Slices', 'period', 5.5),
    ('Intense Craving: Macaroni and Cheese', 'period', 5.5),
    ('Intense Craving: Creamy Fettuccine Alfredo', 'period', 5.5),
    ('Intense Craving: Warm Buttered Toast', 'period', 5.5),
    ('Intense Craving: Buttery Croissant', 'period', 5.5),
    ('Intense Craving: Peanut Butter by the Spoonful', 'period', 5.5),
    ('Intense Craving: Warm Cinnamon Buns', 'period', 5.5),
    ('Intense Craving: Spicy Buffalo Wings', 'period', 5.5),
    ('Preference for Light Refreshment: Fresh Watermelon Wedges', 'ovulation', 5.0),
    ('Preference for Light Refreshment: Crisp Cucumber & Lemon Water', 'ovulation', 5.0),
    ('Preference for Light Refreshment: Açaí Bowl with Berries', 'ovulation', 5.0),
    ('Preference for Light Refreshment: Fresh Avocado Toast with Sprouts', 'ovulation', 5.0),
    ('Preference for Light Refreshment: Chilled Shrimp Cocktail', 'ovulation', 5.0),
    ('Preference for Light Refreshment: Crisp Mixed Greens Salad', 'ovulation', 5.0),
    ('Preference for Light Refreshment: Green Tart Apples', 'ovulation', 5.0),
    ('Preference for Light Refreshment: Chilled Sparkling Water', 'ovulation', 5.0),
    ('Preference for Light Refreshment: Fresh Coconut Water', 'ovulation', 5.0),
    ('Emotional Pattern: Sudden Tearfulness Over Movies/Ads', 'period', 5.5),
    ('Emotional Pattern: Heightened Criticism of Romantic Partner', 'period', 5.5),
    ('Emotional Pattern: Impatience with Slow Drivers/Lines', 'period', 5.5),
    ('Emotional Pattern: Overwhelming Need to Clean Home Alone', 'period', 5.5),
    ('Emotional Pattern: Sense of Despair That Passes in 48 Hours', 'period', 5.5),
    ('Emotional Pattern: Sudden Dismay Looking in Mirror', 'period', 5.5),
    ('Emotional Pattern: Feelings of Loneliness Despite Friends Nearby', 'period', 5.5),
    ('Emotional Pattern: Hyper-Awareness of Flaws', 'period', 5.5),
    ('Emotional Pattern: Refusal to Compromise on Small Matters', 'period', 5.5),
    ('Emotional Pattern: Reluctance to Answer Phone Calls', 'period', 5.5),
    ('Emotional Pattern: Desire to Hide Under Heavy Blankets', 'period', 5.5),
    ('Emotional Pattern: Guilt Over Decreased Productivity', 'period', 5.5),
    ('Emotional Pattern: Craving Unconditional Affection Without Talking', 'period', 5.5),
    ('Emotional Pattern: Sudden Nostalgia for the Past', 'period', 5.5),
    ('Emotional Pattern: Magnetic Charisma & Effortless Humor', 'ovulation', 6.0),
    ('Emotional Pattern: Feeling Desirable & Radiant', 'ovulation', 6.0),
    ('Emotional Pattern: Warm Affection & Generosity Toward Others', 'ovulation', 6.0),
    ('Emotional Pattern: Eagerness to Meet New Acquaintances', 'ovulation', 6.0),
    ('Emotional Pattern: Deep Sexual Arousal from Casual Touches', 'ovulation', 6.0),
    ('Emotional Pattern: Empowered Decision-Making in Career', 'ovulation', 6.0),
    ('Emotional Pattern: Euphoric Appreciation for Music & Art', 'ovulation', 6.0),
    ('Emotional Pattern: Feeling Centered, Capable & Grounded', 'ovulation', 6.0),
    ('Emotional Pattern: Playful Banter & Teasing in Conversation', 'ovulation', 6.0),
    ('Emotional Pattern: Optimistic Ambition for Long-Term Goals', 'ovulation', 6.0),
    ('Emotional Pattern: Feeling Unbothered by Prior Stressors', 'ovulation', 6.0),
    ('Emotional Pattern: Spontaneous Gratitude for Life', 'ovulation', 6.0),
    ('Wardrobe Choice: Flannel Pajama Bottoms Outdoors', 'period', 5.5),
    ('Wardrobe Choice: Dark Stretchy Leggings (Non-Constricting)', 'period', 5.5),
    ('Wardrobe Choice: Oversized Knitted Wool Sweater', 'period', 5.5),
    ('Wardrobe Choice: No Jewelry / Removed All Rings Due to Swelling', 'period', 5.5),
    ('Wardrobe Choice: Flat Walking Sneakers (Zero Heel)', 'period', 5.5),
    ('Wardrobe Choice: High-Waist Seamless Black Shorts', 'period', 5.5),
    ('Wardrobe Choice: Dark Terrycloth Bathrobe Worn All Morning', 'period', 5.5),
    ('Wardrobe Choice: Slip-on Clogs or Slides', 'period', 5.5),
    ('Wardrobe Choice: Unbuttoned Top Button of Pants', 'period', 5.5),
    ('Wardrobe Choice: Loose T-Shirt Dress (No Waist Seam)', 'period', 5.5),
    ('Wardrobe Choice: Backless Silk Halter Top', 'ovulation', 7.5),
    ('Wardrobe Choice: High-Slit Midi or Maxi Skirt', 'ovulation', 7.5),
    ('Wardrobe Choice: Leather or Pleather Fitted Trousers', 'ovulation', 7.5),
    ('Wardrobe Choice: Bright Matching Crop Top & Bottom Set', 'ovulation', 7.5),
    ('Wardrobe Choice: Lace Trimmed Camisole Outing Wear', 'ovulation', 7.5),
    ('Wardrobe Choice: Pointed-Toe High Heel Boots', 'ovulation', 7.5),
    ('Wardrobe Choice: Statement Red or Coral Lipstick', 'ovulation', 7.5),
    ('Wardrobe Choice: Delicate Gold Belly Chain or Anklet', 'ovulation', 7.5),
    ('Wardrobe Choice: Deep V-Neck Sweater or Bodysuit', 'ovulation', 7.5),
    ('Wardrobe Choice: Tailored Blazer Over Sheer Lace Bralette', 'ovulation', 7.5),
    ('Sensory Marker: Hypersensitivity to Strong Perfumes / Cigarette Smoke', 'period', 5.0),
    ('Sensory Marker: Low Sound Tolerance / Muted TV Volume', 'period', 5.0),
    ('Sensory Marker: Need for Dimmed Warm Lighting Indoors', 'period', 5.0),
    ('Sensory Marker: Aversion to Scratchy Clothing Tags / Synthetic Fabrics', 'period', 5.0),
    ('Sensory Marker: Enhanced Gum Sensitivity When Brushing Teeth', 'period', 5.0),
    ('Sensory Marker: Sensitive Scalp When Brushing Hair', 'period', 5.0),
    ('Sensory Marker: Cold Feet Even Under Warm Duvet', 'period', 5.0),
    ('Sensory Marker: Heavy Eyelids & Eye Strain', 'period', 5.0),
    ('Hot Water Bottle Placed on Abdomen', 'period', 8.5),
    ('Herbal Heat Pack Around Lower Back', 'period', 8.0),
    ('Avoiding High-Paced Cardio Workouts', 'period', 6.0),
    ('Slow Walking Only in Nature / Park', 'period', 5.0),
    ('Skipping Heavy Social Dinners', 'period', 6.5),
    ('Canceling Weekend Party Attendance', 'period', 7.0),
    ('Preferring Text Messages Over Voice Calls', 'period', 5.0),
    ('Slipping Feet into Fluffy Fleece Socks', 'period', 5.5),
    ('Wearing Thick Robe Over Clothes Indoors', 'period', 6.0),
    ('Carrying Extra Emergency Menstrual Products in Coat', 'period', 7.5),
    ('Applying Warming Balm / Tiger Balm to Abdomen', 'period', 7.0),
    ('Refusing Any Pants with Zippers or Buttons', 'period', 7.0),
    ('Feeling Clumsy / Dropping Objects Accidentally', 'period', 5.0),
    ('Sore Throat or Mild Runny Nose (Period Flu)', 'period', 6.0),
    ('Heavy Thirst for Warm Beverages Only', 'period', 5.0),
    ('Refusal to Drink Iced Cold Water', 'period', 5.5),
    ('Baking Comfort Pastries or Cookies at Home', 'period', 5.0),
    ('Drinking Mug of Hot Bone Broth', 'period', 5.5),
    ('Dimming Laptop Screen Brightness Down', 'period', 4.5),
    ('Lying in Fetal Position with Knees Hugged to Chest', 'period', 8.0),
    ('Elevating Legs with Pillows in Bed', 'period', 6.0),
    ('Taking Warm Shower to Relieve Lower Back Strain', 'period', 6.5),
    ('Refusal to Wear Underwire Bras of Any Kind', 'period', 7.0),
    ('Complaining of Puffy Cheeks or Morning Face Bloat', 'period', 5.5),
    ('Mild Nausea Upon Waking in Morning', 'period', 6.0),
    ('Difficulty Deciding What to Wear (Nothing Feels Right)', 'period', 5.5),
    ('Self-Conscious About Abdomen Profile in Outfits', 'period', 6.0),
    ('Preferring Dark Dim Lighting in Bedroom', 'period', 4.5),
    ('Canceling Group Fitness Class at Last Minute', 'period', 6.5),
    ('Craving Warm Oatmeal with Honey and Cinnamon', 'period', 5.0),
    ('Eating Warm Soup Instead of Crunchy Salad', 'period', 5.5),
    ('Slow Sluggish Digestive Transit', 'period', 5.5),
    ('Deep Sighing and Yawning Throughout Afternoon', 'period', 5.0),
    ('Overwhelmed by Cluttered Desk or Messy Room', 'period', 5.0),
    ('Withdrawing to Private Room During Social Gathering', 'period', 6.5),
    ('Expressing Feelings of Being Underappreciated', 'period', 5.5),
    ('Holding Tension in Neck, Shoulders and Trapezius', 'period', 5.0),
    ('Craving Warm Melted Cheese Toast', 'period', 5.5),
    ('Refusing to Go Shopping or Run Errands', 'period', 6.0),
    ('Desire for Solitary Quiet Time with Pets', 'period', 5.0),
    ('Styling Hair in High Bouncy Ponytail or Waves', 'ovulation', 6.0),
    ('Applying Scented Shimmer Body Oil to Décolletage', 'ovulation', 7.5),
    ('Choosing Shorter Hemlines / Revealing Outfits', 'ovulation', 8.0),
    ('Wearing Sheer or Form-Accentuating Fabrics', 'ovulation', 8.0),
    ('Eager to Try New Social Spots / Rooftop Bars', 'ovulation', 7.0),
    ('Volunteering to Lead Discussion or Meeting', 'ovulation', 6.0),
    ('Sending Voice Notes with Upbeat Playful Inflection', 'ovulation', 6.0),
    ('Selecting Vibrant Nail Polish (Ruby Red / Magenta)', 'ovulation', 5.5),
    ('Smiling and Greeting Neighbors and Passersby', 'ovulation', 5.5),
    ('Walking with Upright, Confident, Sinuous Posture', 'ovulation', 6.5),
    ('Taking Selfies from Multiple Angles in Good Light', 'ovulation', 6.5),
    ('Applying Lip Plumper or High-Gloss Tint', 'ovulation', 6.5),
    ('Feeling Physically Light and Buoyant While Walking', 'ovulation', 6.0),
    ('Singing Along to Upbeat Pop or R&B Music in Car', 'ovulation', 5.5),
    ('Waking Up Ready to Attack the Day Without Coffee', 'ovulation', 6.0),
    ('Expressing Gratitude for Life and Opportunities', 'ovulation', 5.5),
    ('Ordering Colorful Cocktails / Martinis with Friends', 'ovulation', 6.5),
    ('Wearing Open-Toe Heeled Sandals or Strappy Shoes', 'ovulation', 7.5),
    ('Showing Exposed Collarbones and Shoulders', 'ovulation', 7.0),
    ('Lingering in Conversations with Magnetic Charm', 'ovulation', 7.0),
    ('Spritzing Luxury Floral or Amber Perfume on Neck', 'ovulation', 6.5),
    ('High Enthusiasm for Spontaneous Weekend Plans', 'ovulation', 6.5),
    ('High Physical Motivation During Gym Strength Sets', 'ovulation', 6.5),
    ('Feeling Sexually Alluring and Irresistible', 'ovulation', 8.5),
    ('Checking Reflection with Genuine Delight', 'ovulation', 6.5),
    ('Effortless Banter with Colleagues and Strangers', 'ovulation', 6.0),
    ('Excitement to Plan Vacation or Travel Dates', 'ovulation', 5.5),
    ('Choosing Bright Bold Accessories and Earrings', 'ovulation', 6.0),
    ('Engaging in Playful Touch or Physical Teasing', 'ovulation', 7.5),
    ('Feeling Receptive to Flirtatious Advances', 'ovulation', 8.0),
    ('Natural Flush on Cheeks Without Blush Makeup', 'ovulation', 6.0),
    ('Choosing Form-Fitting Gym Sets (Spandex / Shorts)', 'ovulation', 7.0),
    ('Feeling High Stamina on Long Walks or Dance Floors', 'ovulation', 6.5),
    ('Enjoying Fresh Crisp Salads and Citrus Drinks', 'ovulation', 5.5),
    ('Clear Mind with High Verbal Fluency and Wit', 'ovulation', 6.0),
    ('Feeling Youthful, Vibrant and Full of Vitality', 'ovulation', 6.5),
    ('Eagerness to Reconnect with Friends via Phone', 'ovulation', 5.5),
    ('Choosing Outfits That Accentuate the Waistline', 'ovulation', 7.5),
    ('Desire for Closeness, Romance and Deep Connection', 'ovulation', 7.5),
    ('Expressing Bold Ambitions Without Hesitation', 'ovulation', 6.0),
    ('Sensory Marker: Attraction to Deep Musky / Pheromone Fragrances', 'ovulation', 6.0),
    ('Sensory Marker: Heightened Pleasure from Music Bass Vibrations', 'ovulation', 6.0),
    ('Sensory Marker: Skin Warmth & Tingling Sensation', 'ovulation', 6.0),
    ('Sensory Marker: Enjoyment of Vibrant Sunlight & Outdoor Spaces', 'ovulation', 6.0),
    ('Sensory Marker: Enhanced Taste Perception for Sweet Flavors', 'ovulation', 6.0),
    ('Sensory Marker: Pleasurable Sensitivity to Partner Caresses', 'ovulation', 6.0),
    ('Sensory Marker: Heightened Visual Focus & Mental Clarity', 'ovulation', 6.0),
    ('First Day of Red Blood (Cycle Day 1)', 'period', 10.0),
    ('Heavy Menstrual Flow Day 2 (Super Pad / Regular Change)', 'period', 10.0),
    ('Moderate Menstrual Flow Day 3', 'period', 9.5),
    ('Tapering Menstrual Flow Day 4', 'period', 9.0),
    ('Light Brown Flow Day 5', 'period', 8.5),
    ('Pre-Menstrual Brown Discharge Day -1', 'period', 8.5),
    ('Post-Menstrual Residual Spotting Day 6', 'period', 8.0),
    ('Clotting Observed in Menstrual Blood', 'period', 8.0),
    ('Progesterone Withdrawal Bleeding', 'period', 9.0),
    ('Negative Urine Pregnancy Test Pre-Flow', 'period', 6.0),
    ('Firm, Low, Tightly Closed Cervix', 'period', 7.5),
    ('Thick Sticky White Cervical Discharge (Post-Luteal)', 'period', 7.0),
    ('Cramps Requiring Ibuprofen / NSAIDs', 'period', 8.0),
    ('Cramps Requiring Antispasmodic Medication', 'period', 8.5),
    ('Tiredness Alleviated Only by Lying Flat', 'period', 6.5),
    ('Peak LH Urine Test Ratio > 1.0 (Premom / Clearblue Smile)', 'ovulation', 10.0),
    ('LH Rapid Test Color Equal or Darker Than Control Line', 'ovulation', 10.0),
    ('Translucent Stretchy Cervical Mucus (Stretches 2+ Inches)', 'ovulation', 9.5),
    ('Slippery Watery Discharge Sensation in Underwear', 'ovulation', 9.0),
    ('High Soft Cervix Reached with Difficulty (High in Pelvis)', 'ovulation', 8.5),
    ('Ferning Pattern Observed in Saliva Under Microscope', 'ovulation', 8.5),
    ('Ultrasound Verified Dominant Graafian Follicle (18-22mm)', 'ovulation', 10.0),
    ('Sharp Unilateral Lower Quadrant Stabbing Ache (Mittelschmerz)', 'ovulation', 8.5),
    ('Post-Ovulation 0.3°F to 0.5°F Sustained BBT Rise', 'ovulation', 9.0),
    ('Estrogen Surge Peak Lab Reading', 'ovulation', 9.0),
    ('Heightened Pupil Dilation in Photos', 'ovulation', 5.5),
    ('Increased Cervical Fluid Volume on Toilet Paper', 'ovulation', 8.5)
ON CONFLICT (metric_name) DO UPDATE SET
    phase_association = EXCLUDED.phase_association,
    mathematical_weight = EXCLUDED.mathematical_weight;
